name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  backend:
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install additional libraries
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libudev-dev
          version: 1.0
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0
        with:
          key: docker-${{ runner.os }}-${{ matrix.target }}
      - name: Build release binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.target }}
          args: "--locked --release"
          toolchain: nightly
