name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  backend:
    strategy:
      matrix:
        build:
          - target: x86_64-unknown-linux-gnu
            bin: target/release/serri
          - target: aarch64-unknown-linux-gnu
            bin: target/aarch64-unknown-linux-gnu/release/serri

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install additional libraries
        if: ${{ matrix.build.target == 'x86_64-unknown-linux-gnu' }}
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libudev-dev
          version: 1.0
      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ matrix.build.target }}
      - name: Build release binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          target: ${{ matrix.build.target }}
          args: "--locked --release"
          toolchain: nightly
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ matrix.build.target }}
          path: ${{ matrix.build.bin }}

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Parcel cache
        uses: actions/cache@v4
        with:
          path: .parcel-cache
          key: parcel-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - run: npm ci
      - run: npm run build
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
